yokohamaReflector:
  properties:
    roughness: 0
    metalness: 1
    envMap: studio/studio
    emissiveIntensity: 0
  loadedCallback: reflector/loaded
test_diamond:
  type: refraction
  properties:
    envMap: studio/studio_lowres
    bounces: 3
    ior: 3
    correctMips: true
    fastChroma: true
    aberrationStrength: 0.3
    fresnel: 2
    color: 0x4d8afa
    resolution:
      x: 0
      y: 0
basicring:
  extends: ring
  properties:
    color: 0xdd0000
    roughness: 1
    metalness: 0
ring:
  extends: yokohamaReflector
  properties:
    color: 0xdddddd
    roughness: 0.1
grass:
  extends: yokohamaReflector
  type: physical
  texturePackSource: coast_sand_rocks
  loadedCallback: metalStuds/loadedMaterial
  properties:
    map: diffuse
    displacementMap: displacement
    aoMap: ao
    roughnessMap: roughness
    displacementScale: 0.0
    normalMap: normal
    roughness: 0.5
    metalness: 0.5
error:
  type: physical
  extends: yokohamaReflector
  properties:
    map: common/error
    roughness: 0
    metalness: 1
metal_studs:
  type: physical
  texturePackSource: metal_studs
  extends: yokohamaReflector
  loadedCallback: metalStuds/lodadeMaterial
  properties:
    map: albedo
    normalMap: normal
    aoMap: ao
    metalnessMap: metalness
    color: 0xdddddd
    roughness: 0.1
    metalness: 1
    sheen: 1
doji_diamond:
  type: physical
  texturePackSource: doji
  properties:
    map: diffuse
    emissiveMap: emissive
    roughnessMap: roughness
    envMap: yokohama/group1
    ior: 1.5
    metalness: 0
    transmission: 0.5
arrow:
  type: basic
  properties:
    color: 0xff0000