grass:
  type: physical
  texturePackSource: coast_sand_rocks
  loadedCallback: grass/loadlog
  properties:
    map: diffuse
    displacementMap: displacement
    aoMap: ao
    roughnessMap: roughness
    displacementScale: 0.1
    normalMap: normal
    roughness: 1
    metalness: 0
    envMap: yokohama/group1
