grass:
  type: physical
  texturePackSource: coast_sand_rocks
  properties:
    map: diffuse
    displacementMap: displacement
    aoMap: ao
    roughnessMap: roughness
    displacementScale: 0.1
    normalMap: normal
    roughness: 0
    metalness: 1
    envMap: yokohama/group1
