yokohamaReflector:
  texturePackSource: yokohama
  texturePackSources: [yokohama, coast_sand_rocks]
  properties:
    roughness: 0
    metalness: 1
    envMap: yokohama/group1
grass:
  extends: yokohamaReflector
  type: physical
  texturePackSource: coast_sand_rocks
  loadedCallback: grass/loadlog
  properties:
    map: diffuse
    displacementMap: displacement
    aoMap: ao
    roughnessMap: roughness
    displacementScale: 0.1
    normalMap: normal
