yokohama:
  type: cubemap
  root: ./data/texture/cubemap/yokohama
  defaultExtension: jpg
coast_sand_rocks:
  type: texture
  root: ./data/texture/coast_sand_rocks
  defaultExtension: jpg
  sources:
    - diffuse
    - displacement
    - normal
    - roughness
    - ao
    - arm